#pragma once

typedef enum codeErreur CodeErreur;
enum codeErreur {
	JOUEUR_EXITANT,
	PAS_D_ERREUR,
	ALLOCATION_MEMOIRE,
	OUVERTURE_FICHIER,
	MAUVAIS_CHOIX
};

typedef enum choix Choix;
enum choix {
	CHARGER_JOUEURS_PERSONNAGES,
	AJOUTER_JOUEURS_PERSONNAGES,
	AJOUTER_PERSONNAGES_PERSONNAGES,
	SUPPRIMER_JOUEUR,
	AFFICHER_JOUEUR_PERSONNAGES,
	SAUVER_JOUEUR_PERSONNAGES,
	QUITTER
};